#!/usr/bin/env bash
# Installs nginx and configures it to listen on port 80
# server page "Hello World"
sudo apt-get -y update
sudo apt-get -y intall nginx
echo 'Hello World!' > /var/ww/html/index.nginx-debian.html
sudo service nginx start
