#!/usr/bin/env bash
# Install nginx on web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/^\s*location \/ {/a \ \ \ \ location /redirect_me {\n\ \ \ \ \ \ \ \ return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\ \ \ \ }' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/^\s*server {/a \ \ \ \ error_page 404 /custom_404.html;\n\ \ \ \ location = /custom_404.html {\n\ \ \ \ \ \ \ \ internal;\n\ \ \ \ }' /etc/nginx/sites-available/default
service nginx restart
