#!/usr/bin/env bash
# SIGTERM and SIGQUIT Handler
terminator() {
  echo "I hate the kill command"
  rm -f /var/run/myscript.pid
  exit
}
# SIGINT Handler
sigint_handler() {
  echo "Y U no love me?!"
}
# Write the script to file
echo "$$" > /var/run/myscript.pid
# trap signals set
trap 'sigint_handler' SIGINT
trap 'terminator' SIGTERM
trap 'terminator' SIGQUIT
# Display message indefinately
while true; do
  echo "To infinity and beyond"
  sleep 2
done
