#!/usr/bin/env bash
#Gives you information about the school file
school="school"
if [ ! -e "$school" ]; then
echo "school file does not exist"
exit
else
echo "school file exists"
fi
if [ -s "$school" ]; then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f "$school" ]; then
echo "school is a regular file"
fi
