#!/usr/bin/env bash

# Update package list
sudo apt update

# Install UFW
sudo apt install -y ufw

# Enable UFW
sudo ufw enable

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Show UFW status
sudo ufw status verbose
