#!/usr/bin/env bash
#changes details in /etc/hosts file
cp /etc/hosts ~/hosts_new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts_new
echo '8.8.8.8	facebook.com' >> ~/hosts_new 
cp --force ~/hosts_new /etc/hosts
