#!/usr/bin/env bash
# Restarts apache2 server and serves "Hello Holberton"
# Start Apache service
service apache2 start

# Ensure Hello Holberton page exists
echo "Hello Holberton" > /var/www/html/index.html

# Restart Apache to apply any changes
service apache2 restart
